# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FWa0xKykXMoGNHsoUjsQwlXC54oSfcOR
"""

from flask import Flask, jsonify, request
from flask_cors import CORS

app = Flask(__name__)
CORS(app)  # 允許跨網域存取 (Vercel 連線 Render 必備)


# 定義一個測試用的 API 路由
@app.route('/api/calculate', methods=['POST'])
def calculate():
    # 1. 接收前端傳來的 JSON 資料
    data = request.get_json()

    # 取得前端傳來的數字 (預設為 0)
    x = float(data.get('number', 0))

    # 2. 後端進行 + - * / 運算
    results = {
        'input': x,
        'add_ten': x + 10,
        'minus_five': x - 5,
        'multiply_two': x * 2,
        'divide_two': x / 2 if x != 0 else '無法除以 0',
    }

    # 3. 回傳運算結果 JSON 給前端
    return jsonify({'status': 'success', 'result': results})


if __name__ == '__main__':
    # 在本機測試執行
    app.run(host='0.0.0.0', port=5000, debug=True)